### PR TITLE
updated fonts

### PR DESCRIPTION
**Pull request by dipanshparmar**
Updated fonts and minor adjustments.

### CODE REVIEW

**Comment by dipanshparmar** [comment]
@soniyaprasad77 Please have a look

**Comment by soniyaprasad77** [comment]
It is advisable to employ `rem` units instead of pixels for better scalability, while also ensuring that the initial font size of the website's text remains unchanged. So do the changes.

**Comment by dipanshparmar** [comment]
I did use `rem` for the font-sizes. Do you want `rem` for `margins` and `line-heights` as well?

**Comment by soniyaprasad77** [comment]
Kindly implement the changes according to request. While I value your approach, I've observed that it has led to an increase in font size, as well as disruptions in line height and margins on the website. I prefer to keep the original dimensions intact. Let me illustrate the comparison between the website before and after the adjustments.

***before***

before2
before


***after***

after2
after1

**Comment by dipanshparmar** [comment]
I've reverted the font sizes, line heights, and margins.

**Pull request merged**
