### PR TITLE
[Fix] - #15 - refactor folder structure

### PR DESCRIPTION
**Pull request by Sushannt**
## Pull Request

**Summary:**
Refactor the folder Structure

**Related Issue:**
#15 

**Changes Made:**
1. added `static`, `assets` and `public` folder
   - static
     - css
     - js
   - assets
      - images
      - docs
   - public
      - favicons
3. resume inside `assets/docs`
4. images inside `assets/images`
   - Profile images inside `images/profile`
   - Unused images inside `images/unused`  _ these are the images that are not being used in the project 
5. Renamed `Untitled-images-3 and 4` to `background-image-desktop and mobile`
6. Static folder contains `js` and `css` sub-folders
7. separated  `scrollToTop` script from index.html and put inside `static/js/scrollToTop.js`
8. converted `absolute paths` to `relative paths` for the images

**Screenshots (if applicable):**

**Additional Notes:**
Any other relevant information.

### CODE REVIEW

**Comment by soniyaprasad77** [comment]
Great job, @Sushannt! Just a quick tweak needed in the commit: switch from using **profile** to **Profile** in the `index.html` file. This adjustment will ensure that the profile picture displays correctly. Here's the specific change:

From:
```html
<img src="./assets/images/profile/Photo-to-use.png" />
```

To:
```html
<img src="./assets/images/Profile/Photo-to-use.png" />
```

Additionally, I'd like to request that you remove any unused directories from the  Assets/Images. Thanks!

**Comment by soniyaprasad77** [comment]
Can you please remove the unused directory
?

**Comment by Sushannt** [comment]
Sure, will do, 
do you want the images to remain in the directory or shall i remove the whole directory along with the images inside?

**Comment by soniyaprasad77** [comment]
Yeah, delete all the unused images because it is of no use. Thanks for curating it.

**Comment by soniyaprasad77** [comment]
Amazing work! Thanks for your Contribution. I appreciate it. @Sushannt

**Comment by Esh07** [comment]
The following issue is addressed in this PR:
- #17 

close #17 

Great job @Sushannt  💯 . 

Cheers

**Pull request merged**
